server:
  port: 10003
spring:
  application:
    name: goudong-message-server #微服务名
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8888 # nacos服务集群
  #############
  # rabbitMQ
  ##############
  rabbitmq:
    host: 127.0.0.1  # mq ip地址
    port: 5672 # 端口 默认5672
    username: admin # 用户名
    password: 123456 # 密码
    virtual-host: goudong-host

  ##############
  # 发送邮件配置 #
  #############
  mail:
    host: smtp.qq.com
    username: 1696741038@qq.com
    password: fnlrignacikzcagc
    #   username: 603088455@qq.com
    #   password: jxhfoesryuafbdgh
    port: 587 #端口号465或587
    protocol: smtp
    default-encoding: UTF-8
    smtp:
      connectiontimeout: 5000
      timeout: 3000
      writetimeout: 5000
