server:
  port: 8000
spring:
  application:
    name: education-promote-gateway-server
  cloud:
#    nacos:
#      discovery:
#        server-addr: localhost:8888 #配置nacos地址
    gateway:
      discovery:
        locator:
          enabled: true # 开启从注册中心动态创建路由的功能，利用微服务名进行路由
          #lower-case-service-id: true #使用小写服务名，默认是大写
      routes:
        - id: education-promote-testapi-server
          uri: lb://education-promote-testapi-server
          predicates:
            - Path=/api/test/** #断言，路径相匹配的进行路由
        - id: education-promote-oauth2-server
          uri: lb://education-promote-oauth2-server
          predicates:
            - Path=/api/oauth2/** #断言，路径相匹配的进行路由





ribbon:
  ReadTimeout: 5000 #建立连接所用时间（避免超时）
  ConnectTimeout: 5000 #连接后接口调用时间（避免超时）