server:
  port: 10000
spring:
  application:
    name: goudong-gateway-server
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8888 #配置nacos地址
    gateway:
      discovery:
        locator:
          enabled: true # 开启从注册中心动态创建路由的功能，利用微服务名进行路由
          #lower-case-service-id: true #使用小写服务名，默认是大写
      routes:
        - id: goudong-oauth2-server
          uri: lb://goudong-oauth2-server
          predicates:
            - Path=/oauth2/** #断言，路径相匹配的进行路由
        - id: goudong-message-server
            uri: lb://goudong-message-server
            predicates:
              - Path=/api/message/** #断言，路径相匹配的进行路由

ribbon:
  ReadTimeout: 5000 #建立连接所用时间（避免超时）
  ConnectTimeout: 5000 #连接后接口调用时间（避免超时）
